echo cat.sh
cat cat.sh
echo CMakeLists.txt
cat CMakeLists.txt
echo lv_conf.h
cat lv_conf.h
echo lv_conf_pc.h
cat lv_conf_pc.h
echo lv_conf_stm32.h
cat lv_conf_stm32.h
echo app/CMakeLists.txt
cat app/CMakeLists.txt
echo app/app.c
cat app/app.c
echo app/app.h
cat app/app.h
echo pc/CMakeLists.txt
cat pc/CMakeLists.txt
echo pc/main_pc.c
cat pc/main_pc.c
echo src/fonts/dejavu_24_ru.c
#cat src/fonts/dejavu_24_ru.c
echo src/fonts/dejavu_28_ru.c
#cat src/fonts/dejavu_28_ru.c
